### PR TITLE
🎉 Fix Travis Builds. Upgrade bundler dependency and loosen jekyll requirements

### PR DESCRIPTION
**Pull request by shushugah**
Absent testing coverage (on our ToDo list) we have an example website, which is tested with HTML proofer for any broken links, using explicit and fallback translations. This build now passes @kurtsson 

Next steps are 

1. Add tests
2. Run this build for multiple (or oldest at least) versions of ruby, and multiple versions of jekyll, in order to detect regressions, especially since Jekyll 4.0 is new, and does not have i18n yet

### CODE REVIEW

**Comment by rudygodoy** [comment]
Tested the branch with a Jekyll 4.0 website and it works fine.

**Comment by thomaspeitz** [comment]
@kurtsson / @shushugah - Same for our company - Gem works fine on jekyll 4. Any chance we get a new release of the gem with a merge of this? <3

**Comment by kleuter** [comment]
Please, please release the plugin for 4.0, thanks.

**Comment by shushugah** [comment]
@kurtsson

**Comment by kurtsson** [comment]
Sure! No problem, what would be a good version number for this release?

**Comment by shushugah** [comment]
Yep! None of the PR's have breaking changes, now translations are automatically rebuilt every time page is loaded in developer and links to collections are translated. Rest are test improvements

**Comment by kurtsson** [comment]
> @kurtsson / @shushugah - Same for our company - Gem works fine on jekyll 4. Any chance we get a new release of the gem with a merge of this? <3

v1.6.1 is released with the fixes. Thank you everyone!

**Pull request merged**
